import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://qchzgjhbhnkxkmvebkgw.supabase.co';
const SUPABASE_KEY='sb_publishable_P25yjBAHPfz4zaFzhTZKag_jknlwGKI';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const state={user:null,profile:null,customers:[],loans:[],payments:[],section:'dashboard'};
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const roleLabel=r=>( {admin:'Administrador',supervisor:'Supervisor',collector:'Cobrador',customer:'Cliente'}[r]||r );
function toast(t,error=false){const e=$('#toast');e.textContent=t;e.className='toast on '+(error?'err':'ok');setTimeout(()=>e.className='toast',3500)}
async function profile(){const {data,error}=await sb.from('profiles').select('*').eq('id',state.user.id).single();if(error)throw error;return data}
async function load(){
 const [{data:c,error:ce},{data:l,error:le},{data:p,error:pe}]=await Promise.all([
  sb.from('customers').select('*').order('customer_number'),sb.from('loans').select('*').order('created_at',{ascending:false}),sb.from('payments').select('*').order('paid_at',{ascending:false})]);
 if(ce)throw ce;if(le)throw le;if(pe)throw pe;state.customers=c||[];state.loans=l||[];state.payments=p||[];
}
function shell(){document.body.innerHTML=`<div class="app"><aside class="side"><div class="brand"><span>P</span><div><b>Presta Ya</b><small>Finanzas inteligentes</small></div></div><nav id="nav"></nav><div class="side-bottom"><div class="secure">● Sistema protegido<br><small>Supabase + RLS</small></div><button id="logout" class="ghost">Cerrar sesión</button></div></aside><main><header><div><span class="eyebrow">Panel de control</span><h1 id="title">Dashboard</h1></div><div class="user"><span class="avatar">${esc((state.profile.full_name||'U').slice(0,2).toUpperCase())}</span><div><b>${esc(state.profile.full_name)}</b><small>${roleLabel(state.profile.role)}</small></div></div></header><section id="view"></section></main></div><div id="toast" class="toast"></div>`;buildNav();$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()}}
function buildNav(){const r=state.profile.role;let items=[['dashboard','⌂','Dashboard'],['customers','♙','Clientes'],['loans','▣','Préstamos'],['payments','◉','Pagos']];if(['supervisor','admin'].includes(r))items.push(['approvals','✓','Aprobaciones'],['analysis','◒','Análisis'],['pending','◷','Préstamos pendientes'],['applications','▤','Solicitudes']);if(r==='admin')items.push(['employees','♙','Empleados']);if(['supervisor','admin'].includes(r))items.push(['ids','#','Números de clientes y préstamos']);if(r==='customer')items=[['dashboard','⌂','Mi cuenta'],['loans','▣','Mis préstamos'],['payments','◉','Mis pagos']];$('#nav').innerHTML=items.map(([id,ic,t])=>`<button data-sec="${id}" class="nav ${state.section===id?'active':''}"><i>${ic}</i>${t}</button>`).join('');document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{state.section=b.dataset.sec;buildNav();render()})}
function render(){const r=state.profile.role;const own=r==='customer'?state.customers.filter(x=>x.profile_id===state.user.id):state.customers;const loans=r==='customer'?state.loans.filter(x=>own.some(c=>c.id===x.customer_id)):state.loans;const pays=r==='customer'?state.payments.filter(p=>loans.some(l=>l.id===p.loan_id)):state.payments;const v=$('#view');$('#title').textContent=({dashboard:r==='customer'?'Mi cuenta':'Dashboard',customers:'Clientes',loans:r==='customer'?'Mis préstamos':'Préstamos',payments:r==='customer'?'Mis pagos':'Pagos',approvals:'Aprobaciones',analysis:'Análisis',pending:'Préstamos pendientes',applications:'Solicitudes',employees:'Empleados',ids:'Números de clientes y préstamos'})[state.section]||'Dashboard';
 if(state.section==='dashboard')return dashboard(v,loans,pays,own);if(state.section==='customers')return customers(v,own);if(state.section==='loans')return loansView(v,loans);if(state.section==='payments')return paymentsView(v,pays);if(state.section==='employees')return employees(v);if(state.section==='ids')return ids(v,own,loans);if(state.section==='analysis')return analysis(v,own,loans,pays);if(state.section==='approvals'||state.section==='pending'||state.section==='applications')return workflow(v,state.section,loans);}
function dashboard(v,loans,pays,cs){const active=loans.filter(l=>['approved','active'].includes(l.status));const due=loans.reduce((s,l)=>s+Number(l.total_due||0),0);const paid=pays.reduce((s,p)=>s+Number(p.amount||0),0);v.innerHTML=`<div class="hero"><div><span>RESUMEN OPERATIVO</span><h2>${state.profile.role==='customer'?'Tus finanzas, en un solo lugar':'Una vista clara de tu cartera'}</h2><p>Información actualizada directamente desde tu cuenta.</p></div><button class="primary" onclick="window.newLoan()">+ Nuevo préstamo</button></div><div class="metrics"><div><small>Clientes</small><strong>${cs.length}</strong><em>Registrados</em></div><div><small>Préstamos activos</small><strong>${active.length}</strong><em>En curso</em></div><div><small>Total comprometido</small><strong>${money(due)}</strong><em>Cartera</em></div><div><small>Pagado</small><strong>${money(paid)}</strong><em>Acumulado</em></div></div><div class="grid2"><div class="card"><div class="cardhead"><div><span class="eyebrow">Últimos préstamos</span><h3>Actividad reciente</h3></div><button class="link" onclick="window.go('loans')">Ver todos</button></div>${loans.slice(0,6).map(l=>`<div class="row"><span class="badge">#${esc(l.loan_number)}</span><div class="grow"><b>${money(l.principal)}</b><small>${esc(l.loan_type)} · ${esc(l.status)}</small></div><strong>${money(l.total_due)}</strong></div>`).join('')||'<div class="empty">No hay préstamos todavía.</div>'}</div><div class="card"><div class="cardhead"><div><span class="eyebrow">Pagos</span><h3>Últimos movimientos</h3></div></div>${pays.slice(0,6).map(p=>`<div class="row"><span class="receipt">✓</span><div class="grow"><b>${esc(p.receipt_number)}</b><small>${esc(p.method)} · ${new Date(p.paid_at).toLocaleDateString('es-DO')}</small></div><strong>${money(p.amount)}</strong></div>`).join('')||'<div class="empty">No hay pagos todavía.</div>'}</div></div>`}
function customers(v,cs){v.innerHTML=`<div class="toolbar"><div><span class="eyebrow">CARTERA</span><h2>Clientes</h2></div><button class="primary" onclick="window.newCustomer()">+ Nuevo cliente</button></div><div class="card table"><table><thead><tr><th>N.º Cliente</th><th>Cliente</th><th>Teléfono</th><th>Estado</th><th></th></tr></thead><tbody>${cs.map(c=>`<tr><td><b>#${esc(c.customer_number)}</b></td><td>${esc(c.full_name)}</td><td>${esc(c.phone||'—')}</td><td><span class="status ${c.status}">${esc(c.status)}</span></td><td>›</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay clientes.</td></tr>'}</tbody></table></div>`}
function loansView(v,ls){v.innerHTML=`<div class="toolbar"><div><span class="eyebrow">CARTERA</span><h2>${state.profile.role==='customer'?'Mis préstamos':'Préstamos'}</h2></div><button class="primary" onclick="window.newLoan()">+ Solicitar préstamo</button></div><div class="card table"><table><thead><tr><th>N.º Préstamo</th><th>Cliente</th><th>Principal</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>${ls.map(l=>{const c=state.customers.find(x=>x.id===l.customer_id);return `<tr><td><b>#${esc(l.loan_number)}</b></td><td>${esc(c?.full_name||'—')}</td><td>${money(l.principal)}</td><td>${money(l.total_due)}</td><td><span class="status ${l.status}">${esc(l.status)}</span></td><td>›</td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No hay préstamos.</td></tr>'}</tbody></table></div>`}
function paymentsView(v,ps){v.innerHTML=`<div class="toolbar"><div><span class="eyebrow">MOVIMIENTOS</span><h2>Pagos</h2></div></div><div class="card table"><table><thead><tr><th>Recibo</th><th>Préstamo</th><th>Monto</th><th>Método</th><th>Fecha</th></tr></thead><tbody>${ps.map(p=>{const l=state.loans.find(x=>x.id===p.loan_id);return `<tr><td><b>${esc(p.receipt_number)}</b></td><td>#${esc(l?.loan_number||'—')}</td><td><b>${money(p.amount)}</b></td><td>${esc(p.method)}</td><td>${new Date(p.paid_at).toLocaleDateString('es-DO')}</td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No hay pagos.</td></tr>'}</tbody></table></div>`}
function employees(v){v.innerHTML=`<div class="toolbar"><div><span class="eyebrow">ADMINISTRACIÓN</span><h2>Empleados</h2></div><button class="primary" onclick="window.newEmployee()">+ Nuevo empleado</button></div><div class="card"><div class="empty">Usa el botón para crear usuarios con rol Supervisor o Cobrador. El backend controla los permisos.</div></div>`}
function ids(v,cs,ls){v.innerHTML=`<div class="toolbar"><div><span class="eyebrow">IDENTIFICACIÓN</span><h2>Números de clientes y préstamos</h2></div></div><div class="card table"><table><thead><tr><th>N.º Cliente</th><th>Cliente</th><th>N.º Préstamo</th><th>Estado</th></tr></thead><tbody>${ls.map(l=>{const c=cs.find(x=>x.id===l.customer_id);return `<tr><td><b>#${esc(c?.customer_number||'—')}</b></td><td>${esc(c?.full_name||'—')}</td><td><b>#${esc(l.loan_number)}</b></td><td><span class="status ${l.status}">${esc(l.status)}</span></td></tr>`}).join('')||'<tr><td colspan="4" class="empty">No hay registros.</td></tr>'}</tbody></table></div>`}
function analysis(v,cs,ls,ps){v.innerHTML=`<div class="metrics"><div><small>Clientes</small><strong>${cs.length}</strong></div><div><small>Préstamos</small><strong>${ls.length}</strong></div><div><small>Pagos</small><strong>${ps.length}</strong></div><div><small>Cobrado</small><strong>${money(ps.reduce((s,p)=>s+Number(p.amount||0),0))}</strong></div></div><div class="card"><span class="eyebrow">ANÁLISIS</span><h3>Resumen de cartera</h3><p class="muted">Los indicadores se calculan en tiempo real a partir de los registros de clientes, préstamos y pagos.</p></div>`}
function workflow(v,sec,ls){const wanted=sec==='pending'?'Préstamos pendientes':sec==='approvals'?'Aprobaciones':'Solicitudes';const rows=ls.filter(l=>sec==='pending'?l.status==='pending':l.status==='pending');v.innerHTML=`<div class="toolbar"><div><span class="eyebrow">OPERACIONES</span><h2>${wanted}</h2></div></div><div class="card table"><table><thead><tr><th>Préstamo</th><th>Principal</th><th>Plazo</th><th>Estado</th></tr></thead><tbody>${rows.map(l=>`<tr><td><b>#${esc(l.loan_number)}</b></td><td>${money(l.principal)}</td><td>${esc(l.term_weeks)} semanas</td><td><span class="status pending">Pendiente</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No hay registros pendientes.</td></tr>'}</tbody></table></div>`}
window.go=id=>{state.section=id;buildNav();render()};window.newCustomer=async()=>{const name=prompt('Nombre completo del cliente:');if(!name)return;const {data,error}=await sb.from('customers').insert({full_name:name}).select().single();if(error)return toast(error.message,true);state.customers.push(data);toast('Cliente creado');render()};window.newLoan=()=>toast('El formulario de solicitud se habilitará en la siguiente iteración de operaciones.',false);window.newEmployee=()=>toast('La creación segura de empleados requiere la Edge Function administrativa activa.',false);
async function auth(){const {data:{session}}=await sb.auth.getSession();if(!session)return showLogin();state.user=session.user;try{state.profile=await profile();await load();shell();render()}catch(e){await sb.auth.signOut();showLogin();toast(e.message,true)}}
function showLogin(){document.body.innerHTML=`<div class="login"><div class="login-card"><div class="brand big"><span>P</span><div><b>Presta Ya</b><small>Plataforma financiera</small></div></div><h1>Bienvenido</h1><p>Inicia sesión para acceder a tu cuenta.</p><form id="lf"><input id="identifier" placeholder="Correo o nombre de usuario" required><input id="password" type="password" placeholder="Contraseña" required><button class="primary full">Iniciar sesión</button></form><div class="or">o continúa con</div><div class="social"><button id="google">Google</button><button id="facebook">Facebook</button></div><p class="login-note">Tus datos están protegidos mediante Supabase Auth y políticas RLS.</p></div></div>`;$('#lf').onsubmit=async e=>{e.preventDefault();let id=$('#identifier').value.trim();let email=id;if(!id.includes('@')){const {data,error}=await sb.rpc('resolve_login_email',{p_username:id});if(error||!data)return toast('Usuario no encontrado',true);email=data}const {error}=await sb.auth.signInWithPassword({email,password:$('#password').value});if(error)return toast(error.message,true);location.reload()};['google','facebook'].forEach(id=>$('#'+id).onclick=async()=>{const {error}=await sb.auth.signInWithOAuth({provider:id,options:{redirectTo:location.href}});if(error)toast(error.message,true)});}
auth();