const SUPABASE_URL='https://qchzgjhbhnkxkmvebkgw.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_P25yjBAHPfz4zaFzhTZKag_jknlwGKI';
const EMPLOYEE_CLIENT=()=>import('https://esm.sh/@supabase/supabase-js@2').then(({createClient})=>createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true}}));
function employeeModal(){
 const old=document.getElementById('employee-modal'); if(old)old.remove();
 const m=document.createElement('div');m.id='employee-modal';m.innerHTML=`<div class="modal-backdrop"><form class="modal-card" id="employee-form"><div class="modal-head"><div><span class="eyebrow">ADMINISTRACIÓN</span><h2>Nuevo empleado</h2></div><button type="button" id="employee-close" class="modal-x">×</button></div><label>Nombre completo<input id="em-name" required placeholder="Nombre del empleado"></label><label>Nombre de usuario<input id="em-user" required placeholder="usuario"></label><label>Correo electrónico<input id="em-email" type="email" required placeholder="correo@ejemplo.com"></label><label>Teléfono<input id="em-phone" placeholder="(000) 000-0000"></label><label>Rol<select id="em-role"><option value="supervisor">Supervisor</option><option value="collector">Cobrador</option><option value="customer">Cliente</option></select></label><label>Contraseña<input id="em-pass" type="password" minlength="8" required placeholder="Mínimo 8 caracteres"></label><div class="modal-actions"><button type="button" id="employee-cancel" class="ghost">Cancelar</button><button class="primary">Crear usuario</button></div><p id="employee-msg" class="modal-msg"></p></form></div>`;
 document.body.appendChild(m);['employee-close','employee-cancel'].forEach(id=>document.getElementById(id).onclick=()=>m.remove());
 document.getElementById('employee-form').onsubmit=async e=>{e.preventDefault();const msg=document.getElementById('employee-msg');msg.textContent='Creando usuario...';msg.className='modal-msg';try{const sb=await EMPLOYEE_CLIENT();const {data:{session}}=await sb.auth.getSession();if(!session)throw Error('La sesión de administrador no está activa.');const body={full_name:document.getElementById('em-name').value.trim(),username:document.getElementById('em-user').value.trim(),email:document.getElementById('em-email').value.trim(),phone:document.getElementById('em-phone').value.trim(),role:document.getElementById('em-role').value,password:document.getElementById('em-pass').value};const r=await fetch(SUPABASE_URL+'/functions/v1/admin-create-user',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'No se pudo crear el usuario.');msg.textContent='Usuario creado correctamente.';msg.className='modal-msg success';setTimeout(()=>m.remove(),900)}catch(err){msg.textContent=err.message;msg.className='modal-msg error'}};
}
const watch=()=>{if(window.newEmployee){window.newEmployee=employeeModal;clearInterval(timer)}};const timer=setInterval(watch,100);watch();
