import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://qchzgjhbhnkxkmvebkgw.supabase.co';
const SUPABASE_KEY='sb_publishable_P25yjBAHPfz4zaFzhTZKag_jknlwGKI';
const db=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('es-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const typeLabel=t=>({personal:'Personal',empresarial:'Empresarial'}[t]||t||'');
let loans=[];let payments=[];
function ensureStyles(){if(document.getElementById('payment-ui-style'))return;const s=document.createElement('style');s.id='payment-ui-style';s.textContent=`.payment-action{border:0;background:#1675f5;color:#fff;border-radius:9px;padding:8px 12px;font-weight:800;font-size:11px;cursor:pointer}.payment-action:hover{filter:brightness(.96)}.payment-overlay{position:fixed;inset:0;background:#10203355;backdrop-filter:blur(4px);display:grid;place-items:center;padding:20px;z-index:9999}.payment-card{width:min(520px,100%);background:#fff;border-radius:20px;padding:25px;box-shadow:0 30px 80px #10203333}.payment-card h2{margin:4px 0 6px}.payment-card p{color:#7c8b9d;font-size:12px}.payment-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:18px}.payment-grid label{display:grid;gap:6px;font-size:11px;font-weight:800}.payment-grid input,.payment-grid select,.payment-grid textarea{width:100%;border:1px solid #dce4ed;border-radius:10px;padding:11px;outline:none}.payment-grid textarea{resize:vertical}.payment-full{grid-column:1/-1}.payment-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:20px}.payment-cancel{border:1px solid #dce4ed;background:#fff;border-radius:10px;padding:11px 16px;font-weight:800}.payment-submit{border:0;background:#1675f5;color:#fff;border-radius:10px;padding:11px 17px;font-weight:850}.payment-error{margin-top:12px;background:#fff0f1;color:#b42d3b;padding:10px;border-radius:10px;font-size:11px}.payment-success{margin-top:12px;background:#eaf8f1;color:#168b5b;padding:10px;border-radius:10px;font-size:11px}`;document.head.appendChild(s)}
async function loadData(){const [l,p]=await Promise.all([db.from('loans').select('*').order('created_at',{ascending:false}),db.from('payments').select('loan_id,amount')]);if(!l.error)loans=l.data||[];if(!p.error)payments=p.data||[]}
function paidFor(loanId){return payments.filter(p=>p.loan_id===loanId).reduce((sum,p)=>sum+Number(p.amount||0),0)}
function outstanding(loan){return Math.max(0,Number(loan.total_due||0)-paidFor(loan.id))}
function loanNumberFromRow(row){const first=row.querySelector('td');return first?.textContent?.replace('#','').trim()||''}
function inject(){const title=document.getElementById('title')?.textContent?.trim();if(title!=='Préstamos'&&title!=='Mis préstamos')return;const table=document.querySelector('#view table');if(!table)return;const head=table.querySelector('thead tr');if(head&&!head.querySelector('.payment-head')){const th=document.createElement('th');th.className='payment-head';th.textContent='Acciones';head.appendChild(th)}table.querySelectorAll('tbody tr').forEach(row=>{if(row.querySelector('.payment-action'))return;const number=loanNumberFromRow(row);const loan=loans.find(l=>String(l.loan_number)===number);if(!loan||!['active','approved'].includes(loan.status)||outstanding(loan)<=0)return;const td=document.createElement('td');td.innerHTML='<button type="button" class="payment-action">Registrar pago</button>';row.appendChild(td);td.querySelector('button').onclick=()=>openPayment(loan)})}
function openPayment(loan){document.getElementById('paymentOverlay')?.remove();const balance=outstanding(loan);const ov=document.createElement('div');ov.id='paymentOverlay';ov.className='payment-overlay';ov.innerHTML=`<section class="payment-card"><div><small>PRESTA YA</small><h2>Registrar pago</h2><p>Préstamo <b>#${esc(loan.loan_number)}</b> · ${typeLabel(loan.loan_type)} · Saldo pendiente <b>${money(balance)}</b></p></div><form id="paymentForm"><div class="payment-grid"><label>Monto del pago<input name="amount" type="number" min="0.01" max="${balance.toFixed(2)}" step="0.01" required placeholder="0.00"></label><label>Método<select name="method"><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="zelle">Zelle</option><option value="other">Otro</option></select></label><label class="payment-full">Notas<textarea name="notes" rows="3" placeholder="Observaciones opcionales"></textarea></label></div><div id="paymentError"></div><div class="payment-actions"><button type="button" class="payment-cancel">Cancelar</button><button class="payment-submit">Registrar pago</button></div></form></section>`;document.body.appendChild(ov);ov.querySelector('.payment-cancel').onclick=()=>ov.remove();ov.addEventListener('click',e=>{if(e.target===ov)ov.remove()});ov.querySelector('#paymentForm').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('.payment-submit');btn.disabled=true;btn.textContent='Registrando...';const f=new FormData(e.target);const amount=Number(f.get('amount'));const method=String(f.get('method'));const notes=String(f.get('notes')||'').trim()||null;if(!Number.isFinite(amount)||amount<=0)return fail('Introduce un monto válido.',btn);if(amount>balance)return fail('El monto no puede superar el saldo pendiente.',btn);const {data,error}=await db.rpc('record_payment_transaction',{p_loan_id:loan.id,p_amount:amount,p_method:method,p_installment_id:null,p_notes:notes});if(error)return fail(error.message,btn);const receipt=data?.receipt_number||'Pago registrado';ov.querySelector('#paymentError').className='payment-success';ov.querySelector('#paymentError').textContent=`Pago registrado correctamente. Recibo: ${receipt}`;btn.textContent='Listo';setTimeout(()=>location.reload(),800)};function fail(msg,btn){const box=ov.querySelector('#paymentError');box.className='payment-error';box.textContent=msg;btn.disabled=false;btn.textContent='Registrar pago'}}
async function boot(){ensureStyles();await loadData();inject();new MutationObserver(()=>inject()).observe(document.body,{childList:true,subtree:true});setInterval(async()=>{await loadData();inject()},3000)}
boot();